config/routes.rb
Project2::Application.routes.draw do
  root 'pages#about'
  match '/blog', to: 'pages#blog', via: 'get'
  match '/faq', to: 'pages#faq', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def faq
  end

  def about
  end

  def blog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Developed by Blair Fogeltanz
  </small>
  <nav>
    <ul>
      <li><%= link_to "Faq",   faq_path %></li>
      <li><%= link_to "Blog", blog_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Project 2 App", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Faq",    faq_path %></li>
          <li><%= link_to "Blog", blog_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>This is a Blog about nothing</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="center hero-unit">
<h1>This is a blog about nothing</h1>
<h2><p>Why did you even come here</p></h2>
</div>

app/views/pages/blog.html.erb
<div class="center hero-unit">
<h1>The actual Blog</h1>
</div>
<div class="row">
<div class="span4">
<h2>First Post</h2>
<p>What did you expect. There isn't anything here</p>
</div>
<div class="span4">
<h2>Random Latin</h2>
<p>The next post will be nothing but random latin</p>
</div>
<div class="span4">
<h2>Dat Latin</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo blandit nisi, vel pharetra neque eleifend quis. Nam libero ante, dapibus id ornare in, mollis at est. Nulla mattis sapien vel nisi consequat faucibus. Pellentesque in fringilla erat. Maecenas porta varius erat sit amet tristique. Nulla egestas, lectus eu fermentum tempus, felis elit sodales mauris, id tempus erat elit at tortor. Praesent tristique mollis arcu et facilisis. Sed sed tortor vel dolor vulputate elementum. Integer laoreet ipsum ac tellus commodo, vel accumsan erat mollis. Morbi porta nisl metus, in vulputate lacus dictum ultrices. Quisque nibh nunc, rhoncus commodo lectus nec, laoreet placerat turpis. Sed eget pulvinar quam. Sed pharetra, dolor pretium hendrerit luctus, leo massa iaculis urna, non gravida augue risus id tortor. Proin semper dolor quis posuere fermentum. Nulla suscipit diam eu quam dignissim aliquam. Nullam vitae venenatis diam, eu posuere justo.</p>
</div>

app/views/pages/faq.html.erb
<div class="center hero-unit">
<h1>Frequently Asked Questions?</h1>
</div>
<div class="row">
<div{margin:10px 0px 10px 0px} class="span4 offset4">
<h3>Why did you make this blog?</h3>
<p>I had to as a programing assignment.</p>
<div class="row">
<div{margin:10px 0px 10px 0px} class="span4">
<h3>Why is there no second developer?</h3>
<p>I was unable to find a partner I could meet with.</p>
<div class="row">
<div{margin:10px 0px 10px 0px} class="span4">
<h3>Why more latin?</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse commodo blandit nisi, vel pharetra neque eleifend quis. Nam libero ante, dapibus id ornare in, mollis at est. Nulla mattis sapien vel nisi consequat faucibus. Pellentesque in fringilla erat. Maecenas porta varius erat sit amet tristique. Nulla egestas, lectus eu fermentum tempus, felis elit sodales mauris, id tempus erat elit at tortor. Praesent tristique mollis arcu et facilisis. Sed sed tortor vel dolor vulputate elementum. Integer laoreet ipsum ac tellus commodo, vel accumsan erat mollis. Morbi porta nisl metus, in vulputate lacus dictum ultrices. Quisque nibh nunc, rhoncus commodo lectus nec, laoreet placerat turpis. Sed eget pulvinar quam. Sed pharetra, dolor pretium hendrerit luctus, leo massa iaculis urna, non gravida augue risus id tortor. Proin semper dolor quis posuere fermentum. Nulla suscipit diam eu quam dignissim aliquam. Nullam vitae venenatis diam, eu posuere justo.<p>
</div>
</div>
</div>
</div>
</div>
</div>